### PR TITLE
Move non-assignment scalar array-array ops to scalar util module

### PR DESCRIPTION
**Pull request by saik0**
Straightforward move. No changes to the function bodies, only the method signatures.

One more refactoring after this one, then SIMD PRs start.

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Yup! Nice change, ty!
bors merge

**Comment by saik0** [comment]
> Build failed:
> 
> * [ci (stable)](https://github.com/RoaringBitmap/roaring-rs/runs/4980328814?check_suite_focus=true)

Network failure. We'll be green again after my next PR. Closed.

**Comment by saik0** [comment]
Oh, bors did not, in fact, merge. Reopened.

**Review by Kerollmops — APPROVED** [review]
Trying again!
bors merge

**Pull request merged**
