### PR TITLE
Resolve issues with no std

### LINKED ISSUE #273: E0433 and E0412 for type Vec in 0.10.4
Hi! 

I recently started consuming 0.10.4 and I'm seeing a lot of E0433 and E0412 errors in relation to the `Vec` type when attempting to compile.

Example error output:

```
error[E0433]: failed to resolve: use of undeclared type `Vec`
   --> <removed_path>
    |
197 |     let mut bitmaps = Vec::new();
    |                       ^^^ use of undeclared type `Vec`
    |
help: consider importing this struct
    |
1   + use alloc::vec::Vec;
```

Anyone else experiencing this issue?

### LINKED ISSUE #278: The imports removed in `0.10.4` causes the inability to use `no_std`
The deletions in the [diff](https://github.com/RoaringBitmap/roaring-rs/compare/v0.10.3...v0.10.4) has destroyed support for `no_std` introduced in `v0.10.3`.

You can simply change `Cargo.toml` to reproduce this issue on your local:

```diff
[features]
- default = ["std"]
+ default = []
```

Then you'll find large number of errors caused by `Vec` / `Sized` etc.

Related issue: https://github.com/rust-lang/rust/issues/121362 https://github.com/rust-lang/rust-clippy/issues/12335

The rust community is still working on this lint issue, as a suggestion, @kirk-baird, may you fix the errors?

cc @Kerollmops

**Getting the code to work is more important than clippy's advice.**

### PR DESCRIPTION
**Pull request by kirk-baird**
Should resolve #278 and resolve #273 and also satisfy the clippy lints via cfg flags.

### CODE REVIEW

**Comment by GZTimeWalker** [comment]
LGTM;

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you very much for the changes 🍦

However, to be sure that we don't break the code once again would it be possible to [duplicate this part of the CI](https://github.com/RoaringBitmap/roaring-rs/blob/3fa2e731dc773b6ce92968f50ee75cad80f546e5/.github/workflows/test.yml#L91-L95) and change the parameters to run the tests (or at least compile) in no-std, please?

**Comment by GZTimeWalker** [comment]
Just add this part:

```yaml
- name: Test
  uses: actions-rs/cargo@v1
  with:
    command: test
    args: --no-default-features
```

or 

```yaml
- name: Test
  uses: actions-rs/cargo@v1
  with:
    command: build
    args: --no-default-features
```

**Comment by Kerollmops** [comment]
I would say let's try with the _test_ one, but if it doesn't pass, we can only try to build it.

**Comment by kirk-baird** [comment]
Thanks, I'll try this now and see how it goes.

**Comment by GZTimeWalker** [comment]
It seems that all the checks passed as expected.

**Review by Kerollmops — APPROVED** [review]
Thank you very much, folks 👌 I am merging this. I will do a release once #280 is merged too!

**Pull request merged**
