### PR TITLE
contains_range / range_cardinality functions

### LINKED ISSUE #235: Implement contains_range / range_cardinality functions
Thanks for the all the work put in. 

For my use case I want to test if there is anything set in a given range.

I know I could use rank of upper bound and subtract rank of lower bound
or create a bit set of the range and then call intersection_len
however both these options presumably will be slower than an optimized single call.

I see the java library has methods to get these results.

Would it be possible to implement these methods?

### PR DESCRIPTION
**Pull request by Dr-Emann**
Fixes #235

### CODE REVIEW

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Hey, thank you very much for that, it looks good to me. But would it be possible to add a _quickcheck_ test that:
 - One that creates a RoaringBitmap/Treemap with a random range, adds more numbers into it (in the front and the back of that range) and check that the original range it contained in it.
  - One that does the same but we remove some random numbers from inside this range and check that the range is not contained.

**Comment by Kerollmops** [comment]
Note that I just renamed the master branch to main, you should be careful.

**Comment by Dr-Emann** [comment]
Good call, found a place where I had an off-by-one in the range_cardinality function.

**Review by Kerollmops — APPROVED** [review]
Thank you very much for your work and those new tests.
bors merge

**Pull request merged**
