### PR TITLE
docs: `RoaringTreemap::select` returns `None` if `n >= len()`

### PR DESCRIPTION
**Pull request by shekhirin**
Same as `RoaringBitmap::select`: https://docs.rs/roaring/latest/roaring/bitmap/struct.RoaringBitmap.html#method.select

### CODE REVIEW

**Review by Dr-Emann — APPROVED** [review]
Seems uncontroversial.

**Review by Kerollmops — APPROVED** [review]
Thank you very much!

**Comment by Kerollmops** [comment]
Hey @shekhirin 👋

Indeed. Can you push again? I cannot rerun the job via the Actions page, and it seems that the `jobserver` dependency is failing, and v0.1.28 has been released recently. That could help 🤷‍♂️

**Comment by shekhirin** [comment]
will rebase on top of `main` once the MSRV bump is merged

**Comment by Kerollmops** [comment]
Can you rebase on main, please? 😃

**Comment by shekhirin** [comment]
@Kerollmops done :)

**Review by Kerollmops — APPROVED** [review]

**Pull request merged**
