### PR TITLE
Benchmark datasets

### LINKED ISSUE #129: Sample data for benchmarking
## Summary

The build.rs script fetches one of sample datasets (`wikileaks-noquotes_srt`) on each run. 

_This request is for _some_ mechanism be to have _all_ the datasets in `RoaringBitmap/real-roaring-datasets` reliably available for benchmarking._

## Rationale

It would be helpful to have a canonical perf baseline to ensure new work does not introduce performance regressions.

Many of our existing benchmarks use data that is trivially predicted by the branch predictor. Unfortunately this makes them worse than useless: We are benchmarking the CPU branch predictor rather than our code.

To remedy this: I've been working on a benchmark suite that uses all the sample datasets. Here's a sneak peek of a subset of the report.

Screen Shot 2022-01-09 at 6 19 36 PM

In order for this to be able to be merged, we would need the datasets to be available to the benchmark suite.

## Problems with the current approach:
 * Fetches the datasets specified in build.rs on _every build_
 * Only fetches one dataset

## Potential solutions
 * Check in the unzipped data sets into the repo.
 * Check in the zip files into the repo, unpack them in build.rs
 * Include `RoaringBitmap/real-roaring-datasets` as a git submodule (leave it up to the developer to `git submodule update`) if they want to run benchmarks
 * Add some statefulness to `benchmarks/build.rs` that only fetches when necessary
   * IMO, I like this one least as it's the most work and feels alot like reimplementing `git` or `rsync`

## Considerations
 * How will any potential solution effect CI builds?
 * Could the datasets also be useful for unit testing?

### PR DESCRIPTION
**Pull request by saik0**
Closes #129

Adds CRoaring benchmark datasets. File contents are zstd compressed serialized bitmaps using a shared dictionary. All together adds about 18 MiB.

Utilizing the datasets is out of scope for this PR.

### CODE REVIEW

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Wasn't the initial plan to create a submodule of [the real-roaring-dataset repository](https://github.com/RoaringBitmap/real-roaring-datasets) and to let the user `submodule init/update` by himself?

**Comment by saik0** [comment]
> Wasn't the initial plan to create a submodule of [the real-roaring-dataset repository](https://github.com/RoaringBitmap/real-roaring-datasets) and to let the user `submodule init/update` by himself?

Correct. This avoid a manual step.

Is there some other concern regarding adding these? Would it bloat the size of the published crate?

**Comment by Kerollmops** [comment]
> Correct. This avoid a manual step.

Yup, but cloning the repository is a little issue now, 18Mo of dataset is a lot. Also, I'm not sure that we want to make git care about them. I would prefer that we depend on the official repo, even with a specific revision.

> Is there some other concern regarding adding these? Would it bloat the size of the published crate?

Yup, the other concern is about the size of the repository itself, not the crate as you put the datasets in the benchmark subcrate. I hope that cargo doesn't push useless folders!

**Comment by saik0** [comment]
>  Yup, the other concern is about the size of the repository itself

The difference between this PR and all the zips is rather large  ~18 MB compared to ~95. zstd is ✨ _magic_ ✨
This size reduction was what led me to just include them in the benchmark crate.

> I hope that cargo doesn't push useless folders!

I have verified, [it does not](https://docs.rs/crate/roaring/0.8.1/source/).

My main concern is admittedly a subjective one. It just _feels icky_ 🤢  to introduce a manual fetch step to run benchmarks.

**Comment by Kerollmops** [comment]
> My main concern is admittedly a subjective one. It just _feels icky_ 🤢 to introduce a manual fetch step to run benchmarks.

Maybe we can `git submodule init/update` by ourselves in the `build.rs`. I just checked the size of the repository, not even compressed, it's 628K, adding 18M to that is a lot. The other downside I see is that the user needs to install zstd to be able to run the benchmarks.

I am sure that we can find a solution to this by automating the clone in the `build.rs` script or something.  It could even just be a call to the `git submodule init/update` [`Command`](https://doc.rust-lang.org/std/process/struct.Command.html). What do you think?

**Comment by saik0** [comment]
> The other downside I see is that the user needs to install zstd to be able to run the benchmarks.

This uses the zstd create under the hood, they are decompressed in the benchmark code.

> I just checked the size of the repository, not even compressed, it's 628K, adding 18M to that is a lot.

Valid.

I'm going to close this and explore using `git` binary through `Command` and also check to see if there's some other magic cargo can do. It might make sense to have a _crate_ of datasets.

**Comment by Kerollmops** [comment]
> I'm going to close this and explore using `git` binary through `Command` and also check to see if there's some other magic cargo can do. It might make sense to have a _crate_ of datasets.

BTW, I don't think that creating a crate to store the benchmarks is a great idea: https://github.com/rust-lang/crates.io/issues/195.

**Pull request closed without merging**
