### PR TITLE
Fix potential overflow in deserialization of Bitmap

### PR DESCRIPTION
**Pull request by kirk-baird**
Solves #270

### CODE REVIEW

**Comment by kirk-baird** [comment]
Pushed some fixes for the beta clippy lints.

**Comment by Kerollmops** [comment]
> Pushed some fixes for the beta clippy lints.

Thank you! Could you fix the other clippy issues, please?

**Comment by kirk-baird** [comment]
I think I've got all of the lints this time :crossed_fingers:

**Comment by kirk-baird** [comment]
@Kerollmops looks like the workflows need to be triggered manually

**Pull request merged**
